/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.components.siebel;

import org.junit.Before;
import org.junit.Test;

import org.mule.components.siebel.siebelCloudConnector;

import com.siebel.data.SiebelException;

public class siebelTestCase {
	
	private siebelCloudConnector connector = new siebelCloudConnector();
	
    @Before
    public void setup() throws SiebelException {
    	
        connector.setConnectString("Siebel://159.107.99.49:2321/BIZICRMENTP/SCCObjMgr_enu");
        connector.setUsername("SADMIN");
        connector.setPassword("SADMIN");
        connector.setLanguage("enu");
    }
    
    @Test
    public void invokeSomeMethodOnTheCloudConnector() throws SiebelException {

        connector.createOpportunity("MuleSoft_Opportunity");
        connector.createAccount("MuleSoft_Account");
        connector.updateOpportunityAccount("MuleSoft_Opportunity", "MuleSoft_Account");
        connector.updateOpportunityContact("MuleSoft_Opportunity", "Koray", "Kaydihan");
        connector.deleteOpportunity("MuleSoft_Opportunity");
        connector.deleteAccount("MuleSoft_Account");
    }
}
