/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.components.siebel.config;

import org.mule.api.MuleEvent;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.tck.FunctionalTestCase;

public class siebelNamespaceHandlerTestCase extends FunctionalTestCase {
	
    @Override
    protected String getConfigResources() {
        return"siebel-namespace-config.xml";
    }

    public void testSendMessageToFlow()throws Exception {
    
        SimpleFlowConstruct flow = lookupFlowConstruct("theFlow");
        MuleEvent event = getTestEvent("");
        MuleEvent responseEvent = flow.process(event);    
    }

    private SimpleFlowConstruct lookupFlowConstruct(String name) {
        return(SimpleFlowConstruct)muleContext.getRegistry().lookupFlowConstruct(name);
    }
}

